### ISSUE TITLE
Not automatically reconnecting

### ISSUE THREAD

**Issue by bluewalk** [jlynch630/Harmony.NET#20]
Over time, or when I reboot a switch or AP the library loses connection to the Hub (makes sense right?).
I see there's a TODO about reconnecting upon read failure in `StartListening`. Any idea on when it will be implemented?

When the connection breaks the following exception is generated
```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Sockets.SocketException
   at System.Net.Sockets.Socket.BeginSend(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.AsyncCallback, System.Object)
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[], Int32, Int32, System.AsyncCallback, System.Object)

Exception Info: System.IO.IOException
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[], Int32, Int32, System.AsyncCallback, System.Object)
   at System.IO.Stream+<>c.<BeginEndWriteAsync>b__53_0(System.IO.Stream, ReadWriteParameters, System.AsyncCallback, System.Object)
   at System.Threading.Tasks.TaskFactory`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FromAsyncTrim[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.IO.Stream+ReadWriteParameters, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, ReadWriteParameters, System.Func`5<System.__Canon,ReadWriteParameters,System.AsyncCallback,System.Object,System.IAsyncResult>, System.Func`3<System.__Canon,System.IAsyncResult,System.Threading.Tasks.VoidTaskResult>)
   at System.IO.Stream.BeginEndWriteAsync(Byte[], Int32, Int32)
   at System.IO.Stream.WriteAsync(Byte[], Int32, Int32, System.Threading.CancellationToken)
   at System.Net.WebSockets.Managed.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode, Boolean, System.ArraySegment`1<Byte>)

Exception Info: System.Net.WebSockets.WebSocketException
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Net.WebSockets.Managed.ManagedWebSocket+<SendCloseFrameAsync>d__68.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Net.WebSockets.Managed.ManagedWebSocket+<CloseAsyncPrivate>d__67.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Harmony.WebSockets.WebSocketConnection+<Disconnect>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
  ...
```

**Comment by bluewalk** [comment]
Also, connecting to an IP/hub that doesn't respond results in the following exception:
```
Type: System.Net.WebSockets.WebSocketException
 - Message: Unable to connect to the remote server
 - Source: System.Net.WebSockets.Client.Managed
 - Stacktrace:    at System.Net.WebSockets.Managed.WebSocketHandle.<ConnectAsyncCore>d__24.MoveNext()
```
